Do not allow forked repos to push back commits. Display better error message

diff --git a/.github/workflows/routine.yaml b/.github/workflows/routine.yaml
--- a/.github/workflows/routine.yaml
+++ b/.github/workflows/routine.yaml
@@ -126,21 +126,35 @@ jobs:
         with:
           name: routine
 
+      - name: Verify no un-pushed commits (main, fork)
+        if: |
+          (
+            github.event_name == 'push' &&
+            github.event.base_ref == format('refs/head/{0}', github.event.repository.default_branch)
+          ) ||
+          (
+            github.event_name == 'pull_request' &&
+            github.event.pull_request.head.repo.fork
+          )
+        run: |
+          echo "${{ toJSON(github.event) }}"
+          if [ -n "`git cherry origin/$(git name-rev --name-only HEAD)`" ]; then
+            echo "Un-pushed commits:"
+            git cherry -v origin/$(git name-rev --name-only HEAD)
+            if [ "${{ github.event_name }}" == "pull_request" ]; then
+              STATEMENT="GHA is not allowed to push commits back to a forked repo. Please perform and commit these actions manually."
+            else
+              STATEMENT="GHA should not auto-push to the HEAD branch. Please make a PR to have the changes be collected."
+            fi
+            echo "::error:: Some auto generated commits were found. $STATEMENT Exiting"
+            exit 1
+          fi
+
       - name: Git Push (PR)
         uses: r-lib/actions/pr-push@v1
         if: github.event_name == 'pull_request'
         with:
           repo-token: ${{ github.token }}
-      - name: Verify no un-pushed commits (main)
-        if: github.event_name == 'push'
-        run: |
-          # Do not push to main branch
-          if [ -n "`git cherry origin/HEAD`" ]; then
-            echo "Un-pushed commits:"
-            git cherry -v origin/HEAD
-            echo "::error:: Some auto generated commits were found. GHA should not auto-push to the HEAD branch. Please make a PR to have the changes be collected. Exiting"
-            exit 1
-          fi
 
       # Execute these steps after pushing, as
       # no updated files will be commited back to GitHub
